### ISSUE TITLE
Bot is crashing

### ISSUE THREAD

**Issue by fulviodenza** [SakoDroid/telego#21]
Hi, the bot is crashing due to a library internal issue:
```
____    __

/ __/___/ /  ___

/ _// __/ _ \/ _ \

/___/\__/_//_/\___/ v3.3.10-dev

High performance, minimalist Go web framework

https://echo.labstack.com/

____________________________________O/_______

O\

⇨ http server started on [::]:8080

2024/04/05 16:43:28 | Update				my_chat_member |Parsed

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x268 pc=0xc79619]

goroutine 105 [running]:

github.com/SakoDroid/telego/v2/parser.checkHandlers(0xf1b6ff?)

/go/pkg/mod/github.com/!sako!droid/telego/v2@v2.1.0/parser/handlers.go:67 +0x19

github.com/SakoDroid/telego/v2/tba.CreateInterface.GetUpdateParserMiddleware.func1(0xc00032a580, 0xc000406780?)

/go/pkg/mod/github.com/!sako!droid/telego/v2@v2.1.0/parser/updateParser.go:24 +0x1b2

github.com/SakoDroid/telego/v2/parser.(*middlewareListMember).execute(0xc0002b1110, 0xc00032a580)

/go/pkg/mod/github.com/!sako!droid/telego/v2@v2.1.0/parser/middlewareList.go:17 +0x71

github.com/SakoDroid/telego/v2/parser.(*middlewareLinkedList).executeChain(...)

/go/pkg/mod/github.com/!sako!droid/telego/v2@v2.1.0/parser/middlewareList.go:44

github.com/SakoDroid/telego/v2/parser.ExecuteChain(0xc000128cc0?)

/go/pkg/mod/github.com/!sako!droid/telego/v2@v2.1.0/parser/updateParser.go:14 +0x25

created by github.com/SakoDroid/telego/v2/tba.(*BotAPIInterface).ParseUpdate in goroutine 115

/go/pkg/mod/github.com/!sako!droid/telego/v2@v2.1.0/tba/TBAInterface.go:125 +0x14a

exit status 2
```

This is happening after the bot has been added to a group, although the bot is enabled like this:
```
		b.TelegramClient.AddHandler(c, func(u *objs.Update) {
			if strings.Contains(c, "start") || strings.Contains(c, "hi") {
				kb := b.TelegramClient.CreateKeyboard(false, false, false, false, "type ...")

				kb.AddButton("/help", 1)
				kb.AddButton("/register", 1)
				kb.AddButton("/getdefaultpage", 2)

				_, err := b.TelegramClient.AdvancedMode().ASendMessage(u.Message.Chat.Id, "Welcome to notion-echo bot!", "", u.Message.MessageId, 0, false, false, nil, false, false, kb)
				if err != nil {
					fmt.Println(err)
				}
			}
			if strings.Contains(u.Message.Text, c) || strings.Contains(u.Message.Caption, c) {
				f(ctx, u)
			}
		}, utils.PRIVATE_CHAT_TYPE, utils.GROUP_CHAT_TYPE, utils.SUPERGROUP_CHAT_TYPE)
```

to listen to groups and supergroups too. I've tried to go in debug mode but I think there is some panicking goroutine and I was not able to observe the panic.
For more details about the bot, it's this: https://github.com/fulviodenza/notion-echo/blob/main/bot/bot.go 

It looks like this:
```
	if up.Message.UserShared != nil {
		return checkUserSharedHandlers(up)
	}
```
is the incriminated line, maybe `Message` or `up` are nil and then accessing to the next field could make the bot panic.

**Comment by fulviodenza** [comment]
This is making me loosing users for the bot, i will change the library if there will be no release or no pr approval

**Comment by fulviodenza** [comment]
For anyone having issues this is my fork: https://github.com/fulviodenza/telego

**Comment by SakoDroid** [comment]
Hello @fulviodenza .
I'm super sorry for the delay, i'm preoccupied these days and completely forgot about this.
I have a suggestion, do you wanna maintain this library since i don't have enough time?

**Comment by fulviodenza** [comment]
yeah this makes sense to me, let's talk somewhere, give me a contact if you want.
Hear you soon

**Comment by SakoDroid** [comment]
Sure, yeah.
This is my email : rezafattahi85@hotmail.com
