### ISSUE TITLE
How do i get a user's location

### ISSUE THREAD

**Issue by ObiajuluM** [SakoDroid/telego#4]
How do i request a user's location? and get user id

**Comment by SakoDroid** [comment]
To get location :
Location is located in the message struct. You can register a channel for "message" updates and then access the location (update.Message.Location). Before that you can send a message and ask the user for location.

To get user id :
You can get a user's id using "From" field. "From" field contains the information of the user that has sent the messags. For example in a messags type update you can access the id like this :
update.Message.From.Id

**Comment by ObiajuluM** [comment]
Thanks

**Comment by SakoDroid** [comment]
Anytime!

**Comment by ObiajuluM** [comment]
Concerning the location i get an error each time I make a request
```
func locate() {
	bot.AddHandler("locale", func(u *objs.Update) {
		_, err := bot.SendMessage(u.Message.Chat.Id, fmt.Sprint(u.Message.Location.LivePeriod), "", u.Message.MessageId, false, false)
		if err != nil {
			log.Panic(err)
		}
	}, "private")
}
```


error message: 
```
2022/04/08 05:09:05 | getWebhookInfo                    Success |610782µs
2022/04/08 05:09:06 | Update                            message |Parsed
2022/04/08 05:09:06 | Update                            message |Parsed
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x7e37ee]

goroutine 10 [running]:
main.locate.func1(0xc00014c400)
        C:/Users/0xEarl/Desktop/Tgo - Copy/main.go:44 +0x2e
created by github.com/SakoDroid/telego/parser.checkTextMsgHandlers
        C:/Users/0xEarl/go/pkg/mod/github.com/!sako!droid/telego@v1.7.2/parser/handlers.go:61 +0xd8
exit status 2

C:\Users\0xEarl\Desktop\Tgo - Copy>

```

**Comment by ObiajuluM** [comment]
Concerning the location i get an error each time I make a request
```
func locate() {
	bot.AddHandler("locale", func(u *objs.Update) {
		_, err := bot.SendMessage(u.Message.Chat.Id, fmt.Sprint(u.Message.Location.LivePeriod), "", u.Message.MessageId, false, false)
		if err != nil {
			log.Panic(err)
		}
	}, "private")
}
```
error message:
```
2022/04/08 05:09:05 | getWebhookInfo                    Success |610782µs
2022/04/08 05:09:06 | Update                            message |Parsed
2022/04/08 05:09:06 | Update                            message |Parsed
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x7e37ee]

goroutine 10 [running]:
main.locate.func1(0xc00014c400)
        C:/Users/0xEarl/Desktop/Tgo - Copy/main.go:44 +0x2e
created by github.com/SakoDroid/telego/parser.checkTextMsgHandlers
        C:/Users/0xEarl/go/pkg/mod/github.com/!sako!droid/telego@v1.7.2/parser/handlers.go:61 +0xd8
exit status 2

C:\Users\0xEarl\Desktop\Tgo - Copy>

```

**Comment by ObiajuluM** [comment]
> To get location : Location is located in the message struct. You can register a channel for "message" updates and then access the location (update.Message.Location). Before that you can send a message and ask the user for location.
> 
> To get user id : You can get a user's id using "From" field. "From" field contains the information of the user that has sent the message. For example in a message type update, you can access the id like this : update.Message.From.Id

How do I go about it

**Comment by ObiajuluM** [comment]
i think i have gotten it

```
func locate() {

	//The general update channel.

	//Adding a handler. Everytime the bot receives message "hi" in a private chat, it will respond "hi to you too".

	bot.AddHandler("hi", func(u *objs.Update) {

		//Register channel for receiving messages from this chat.
		cc, _ := bot.AdvancedMode().RegisterChannel(strconv.Itoa(u.Message.Chat.Id), "message")

		//Sends back a message
		_, err := bot.SendMessage(u.Message.Chat.Id, "hi to you too, send me a location", "", u.Message.MessageId, false, false)
		if err != nil {
			fmt.Println(err)
		}

		var loction objs.Location

		//Waits for an update from this chat
		up := <-*cc
		if reflect.TypeOf(u.Message.Location) != reflect.TypeOf(loction) {
			locate()
		}

		//Sends back the received location
		_, err = bot.SendLocation(up.Message.Chat.Id, false, false, up.Message.Location.Latitude, up.Message.Location.Longitude, up.Message.Location.HorizontalAccuracy, up.Message.MessageId)

		if err != nil {
			fmt.Println(err)
		}
	}, "private")
}
```
